apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: monitor-gokitconsul
 labels:
   prometheus: kube-prometheus
 namespace: monitoring
spec:
 selector:
   matchLabels:
     tag: gokitconsul
 namespaceSelector:
   matchNames:
   - default
   - test
 endpoints:
 - port: metrics
   interval: 10s
